apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: helloworld
  name: activemq-deployment
  labels:
    app: hello_world_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello_world_app
  template:
    metadata:
      labels:
        app: hello_world_app
    spec:
      containers:
      - image: "rmohr/activemq:latest"
        name: activemq
        imagePullPolicy: Always