apiVersion: v1
kind: Service
metadata:
  name: activemq-service
  namespace: helloworld
  labels:
    app: hello_world_app
spec:
  selector:
    app: hello_world_app
  ports:
  - name: dashboard
    port: 8161
    targetPort: 8161
    protocol: TCP
  - name: openwire
    port: 61616
    targetPort: 61616
    protocol: TCP
  type: LoadBalancer